<table width=100%>
<tr>
    <td><h1 style="text-align: left; font-size:300%;">
        Introduction to Pandas
    </h1></td>
    <td width="50%">
    <div style="text-align: right">
    <b> Practical Data Science Lessons</b><br><br>
    <b> Riccardo Bertoglio</b><br>
    <a href="mailto:riccardo.bertoglio@polimi.it">riccardo.bertoglio@polimi.it</a><br>
    </div>
</tr>
</table>

## Learning outcomes 🔎


*   [What is Pandas?](#what_is_pandas)
*   [Pandas Data Structures](#pandas_data_structures)
*   [Data Import and Export](#data_import_export)
*   [Data Exploration](#data_exploration)
*   [Indexing and Selecting Data](#indexing_selecting_data)
*   [Assigning Data](#assigning_data)
*   [Adding and deleting columns](#adding_deleting_columns)
*   [Grouping](#grouping)
*   [Merging](#merging)

#### More difficult topics are marked with the climbing icon 🧗
**Nerdy stuff is marked with** 🤓

#### Resources:
*   *[Pandas user guide](https://pandas.pydata.org/docs/user_guide/index.html)*
    *   *[10 minutes to Pandas](https://pandas.pydata.org/docs/user_guide/10min.html)*
    *   *[Intro to data structures](https://pandas.pydata.org/docs/user_guide/dsintro.html#)*
    *   *[Essential basic functionality](https://pandas.pydata.org/docs/user_guide/basics.html#)*
    *   *[Cookbook - Short and sweet examples and links for useful pandas recipes](https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html)* 

<a id='what_is_pandas'></a>
## What is Pandas? 🐼

Pandas is an open-source Python library that provides easy-to-use data structures and data analysis tools for data manipulation and analysis. It is **one of the most widely used libraries for data analysis in the Python** ecosystem and is particularly popular in fields such as data science and machine learning.

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy arrays in which the **rows and columns are identified with labels** rather than simple integer indices. This improves flexibility in data manipulation and allows to perform database-like operations on arrays.

🤓 For more detailed information, [read here](https://pandas.pydata.org/docs/getting_started/overview.html)

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd

<a id='pandas_data_structures'></a>
## Pandas Data Structures

Pandas provides two types of classes for handling data:
* **Series**: a one-dimensional labeled array holding data of any type such as integers, strings, Python objects etc.
* **DataFrame**: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

### Series

Series is a **one-dimensional labeled array capable of holding any data type** (integers, strings, floating point numbers, Python objects, etc.). **Like a NumPy array, a pandas Series has a single dtype**. The axis labels are collectively referred to as the index. The basic method to create a Series is to call:
```
s = pd.Series(data, index=index)
```

Here, data can be many different things:
* a Python dict
* an ndarray
* an iterable (lists, tuples, strings, etc.)
* a scalar value (like 5)

The passed index is a list of axis labels.

In [3]:
s = pd.Series([25, 50, 75, 100])
s
type(s)

0     25
1     50
2     75
3    100
dtype: int64

pandas.core.series.Series

You can assign row labels using the `index` parameter. A Series is, in essence, a single column of a DataFrame. However, a Series does not have a column name, it only has one overall `name`:

In [4]:
s = pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')
s

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

The Series and the DataFrame are intimately related. It's helpful to think of a DataFrame as actually being just a bunch of Series "glued together".

Pandas Series can be splitted into the index part and the data part using the `index` and `array` attributes.

In [5]:
s.array

type(s.array)

<PandasArray>
[30, 35, 40]
Length: 3, dtype: int64

pandas.core.arrays.numpy_.PandasArray

In [6]:
s.index

type(s.index)

Index(['2015 Sales', '2016 Sales', '2017 Sales'], dtype='object')

pandas.core.indexes.base.Index

🤓 **Note**: In the past, pandas recommended `Series.values` or `DataFrame.values` for extracting the data from a Series or DataFrame. You’ll still find references to these in old code bases and online. The current recommendation is avoiding `.values` and using `.array` or `.to_numpy()`. `.values` has some drawbacks [explained here](https://pandas.pydata.org/docs/user_guide/basics.html#attributes-and-underlying-data)

#### Series is ndarray-like
Series acts very similarly to a ndarray and is a valid argument to most NumPy functions. However, operations such as slicing will also slice the index.

In [7]:
s[1:3]

2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

#### Series is dict-like
A Series is also like a fixed-size dict in that you can get and set values by index label:

In [8]:
s["2016 Sales"]

35

### DataFrame

DataFrame is a **2-dimensional labeled data structure with columns of potentially different types**. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object. Like Series, DataFrame accepts many different kinds of input:
* Dict of 1D ndarrays, lists, dicts, or Series
* 2-D numpy.ndarray
* Structured or record ndarray
* A Series
* Another DataFrame

Along with the data, you can optionally pass index (row labels) and columns (column labels) arguments. If you pass an index and / or columns, you are guaranteeing the index and / or columns of the resulting DataFrame. Thus, a dict of Series plus a specific index will discard all data not matching up to the passed index.

If axis labels are not passed, they will be constructed from the input data based on common sense rules.

Let's create a simple DataFrame from a dict of lists:

In [9]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

Yes   No
0   50  131
1   21    2

DataFrame entries are not limited to integers. For instance, here's a DataFrame whose values are strings:

In [10]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

The constructor assigns an ascending count from 0 (0, 1, 2, 3, ...) for the *row labels*. Sometimes this is OK, but oftentimes we will want to assign these labels ourselves. So, we can assign an `index` using the proper parameter:

In [11]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

You can also create a DataFrame by using a list of lists and specify the column lables with the `columns` parameter:

In [12]:
cities = pd.DataFrame(
    [
        ['California', 39512223, 423967, 'West'],
        ['Washington', 7614893, 184661, 'West'],
        ['New York', 19453561, 141297, 'Est'],
        ['North Carolina', 10488084, 139391, 'Est'],
        ['Florida', 21477737, 170312, 'Est']
    ],
    columns=['name', 'population', 'area', 'position']
)
cities

name  population    area position
0      California    39512223  423967     West
1      Washington     7614893  184661     West
2        New York    19453561  141297      Est
3  North Carolina    10488084  139391      Est
4         Florida    21477737  170312      Est

<a id='data_import_export'></a>
## Data Import and Export

Being able to create a DataFrame or Series by hand is handy. But, most of the time, we won't actually be creating our own data by hand. Instead, we'll be working with data that already exists.

Data can be stored in any of a number of different forms and formats. By far the most basic of these is the humble CSV file. When you open a CSV file you get something that looks like this:

```
Product A,Product B,Product C
30,21,9
35,34,1
41,11,11
```

So a CSV file is a table of values separated by commas. Hence the name: "Comma-Separated Values", or CSV.

Let's now set aside our toy datasets and see what a real dataset looks like when we read it into a DataFrame. We'll use the `pd.read_csv()` function to read the Wine Reviews data into a DataFrame. 

The Wine Reviews dataset contains reviews scraped on the web with variety, location, winery, price, and description from sommelier. 

In [14]:
wine_reviews = pd.read_csv("data/winemag-data-130k-v2.csv")
wine_reviews.head()  # function to print the first rows

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

**Not only CSV!**

[Image source.](https://pandas.pydata.org/docs/getting_started/intro_tutorials/02_read_write.html)

After performing some data manipulation, we may want to save the data to a CSV file. We can use the function `DataFrame.to_csv()`:

In [17]:
wine_reviews.to_csv("exported_wine_reviews.csv")

The `pd.read_csv()` function has over 30 optional parameters you can specify. For example, you can see in this dataset that the CSV file has a built-in index, which pandas did not pick up on automatically. To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an `index_col`:

In [18]:
wine_reviews = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0)
wine_reviews.head()

country                                        description  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

[Refer to the official documentation for the complete list of parameters.](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

<a id='data_exploration'></a>
## Data Exploration

### Attributes and underlying data

pandas objects have a number of attributes enabling you to access the metadata
* **shape**: gives the axis dimensions of the object, consistent with ndarray
* **Axis labels**:
  * **Series**: **index** (only axis)
  * **DataFrame**: **index** (rows) and **columns**

**Note, these attributes can be safely assigned to!**

In [19]:
wine_reviews.shape

wine_reviews.index

wine_reviews.columns

(129971, 13)

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

In [20]:
# Rewrite the column names in capital letters
wine_reviews.columns = [x.upper() for x in wine_reviews.columns]
wine_reviews.columns

Index(['COUNTRY', 'DESCRIPTION', 'DESIGNATION', 'POINTS', 'PRICE', 'PROVINCE',
       'REGION_1', 'REGION_2', 'TASTER_NAME', 'TASTER_TWITTER_HANDLE', 'TITLE',
       'VARIETY', 'WINERY'],
      dtype='object')

### Viewing the data

To view a small sample of a Series or DataFrame object, use the `head()` and `tail()` methods. The default number of elements to display is five, but you may pass a custom number.

In [21]:
wine_reviews.head()

COUNTRY                                        DESCRIPTION  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          DESIGNATION  POINTS  PRICE           PROVINCE  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              REGION_1           REGION_2         TASTER_NAME  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  TASTER_TWITTER_HANDLE                                              TITLE  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          VARIETY               WINERY  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

In [22]:
wine_reviews.tail(2)

COUNTRY                                        DESCRIPTION  \
129969  France  A dry style of Pinot Gris, this is crisp with ...   
129970  France  Big, rich and off-dry, this is powered by inte...   

                          DESIGNATION  POINTS  PRICE PROVINCE REGION_1  \
129969                            NaN      90   32.0   Alsace   Alsace   
129970  Lieu-dit Harth Cuvée Caroline      90   21.0   Alsace   Alsace   

       REGION_2 TASTER_NAME TASTER_TWITTER_HANDLE  \
129969      NaN  Roger Voss            @vossroger   
129970      NaN  Roger Voss            @vossroger   

                                                    TITLE         VARIETY  \
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                      WINERY  
129969  Domaine Marcel Deiss  
129970      Domaine Schoffit

The method `info()` provides technical information about a DataFrame:

In [23]:
wine_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   COUNTRY                129908 non-null  object 
 1   DESCRIPTION            129971 non-null  object 
 2   DESIGNATION            92506 non-null   object 
 3   POINTS                 129971 non-null  int64  
 4   PRICE                  120975 non-null  float64
 5   PROVINCE               129908 non-null  object 
 6   REGION_1               108724 non-null  object 
 7   REGION_2               50511 non-null   object 
 8   TASTER_NAME            103727 non-null  object 
 9   TASTER_TWITTER_HANDLE  98758 non-null   object 
 10  TITLE                  129971 non-null  object 
 11  VARIETY                129970 non-null  object 
 12  WINERY                 129971 non-null  object 
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB


The `describe()` method shows a quick statistic summary of your data. It is type-aware, meaning that its output changes based on the data type of the input:

In [24]:
# describe only the numerical columns
wine_reviews.describe()

POINTS          PRICE
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [25]:
# describe all the columns
wine_reviews.describe(include='all')

COUNTRY                                        DESCRIPTION DESIGNATION  \
count   129908                                             129971       92506   
unique      43                                             119955       37979   
top         US  Seductively tart in lemon pith, cranberry and ...     Reserve   
freq     54504                                                  3        2009   
mean       NaN                                                NaN         NaN   
std        NaN                                                NaN         NaN   
min        NaN                                                NaN         NaN   
25%        NaN                                                NaN         NaN   
50%        NaN                                                NaN         NaN   
75%        NaN                                                NaN         NaN   
max        NaN                                                NaN         NaN   

               POINTS          PRICE    PROVINCE     REGION_1       REGION_2  \
count   129971.000000  120975.000000      129908       108724          50511   
unique            NaN            NaN         425         1229             17   
top               NaN            NaN  California  Napa Valley  Central Coast   
freq              NaN            NaN       36247         4480          11065   
mean        88.447138      35.363389         NaN          NaN            NaN   
std          3.039730      41.022218         NaN          NaN            NaN   
min         80.000000       4.000000         NaN          NaN            NaN   
25%         86.000000      17.000000         NaN          NaN            NaN   
50%         88.000000      25.000000         NaN          NaN            NaN   
75%         91.000000      42.000000         NaN          NaN            NaN   
max        100.000000    3300.000000         NaN          NaN            NaN   

       TASTER_NAME TASTER_TWITTER_HANDLE  \
count       103727                 98758   
unique          19                    15   
top     Roger Voss            @vossroger   
freq         25514                 25514   
mean           NaN                   NaN   
std            NaN                   NaN   
min            NaN                   NaN   
25%            NaN                   NaN   
50%            NaN                   NaN   
75%            NaN                   NaN   
max            NaN                   NaN   

                                                    TITLE     VARIETY  \
count                                              129971      129970   
unique                                             118840         707   
top     Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...  Pinot Noir   
freq                                                   11       13272   
mean                                                  NaN         NaN   
std                                                   NaN         NaN   
min                                                   NaN         NaN   
25%                                                   NaN         NaN   
50%                                                   NaN         NaN   
75%                                                   NaN         NaN   
max                                                   NaN         NaN   

                    WINERY  
count               129971  
unique               16757  
top     Wines & Winemakers  
freq                   222  
mean                   NaN  
std                    NaN  
min                    NaN  
25%                    NaN  
50%                    NaN  
75%                    NaN  
max                    NaN

For object data (e.g. strings or timestamps), the result’s index will include `count`, `unique`, `top`, and `freq`. The `top` is the most common value. The `freq` is the most common value’s frequency. Timestamps also include the `first` and `last` items.

In [26]:
# describe a specific column
wine_reviews["TASTER_NAME"].describe() 

count         103727
unique            19
top       Roger Voss
freq           25514
Name: TASTER_NAME, dtype: object

If you want to get some particular simple summary statistic about a column in a DataFrame or a Series, there is usually a helpful pandas function that makes it happen. 

For example, to see the mean of the points allotted (e.g. how well an averagely rated wine does), we can use the `mean()` function:

In [27]:
wine_reviews["POINTS"].mean()

88.44713820775404

To see a list of unique values we can use the `unique()` function:

In [28]:
wine_reviews["TASTER_NAME"].unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

To see a list of unique values _and_ how often they occur in the dataset, we can use the `value_counts()` method:

In [29]:
wine_reviews["TASTER_NAME"].value_counts()

TASTER_NAME
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

<a id='indexing_selecting_data'></a>
## Indexing and Selecting Data

### Attribute access
You may access an index on a Series or column on a DataFrame directly as an attribute. Hence to access the `country` property of `wine_reviews` we can use:

In [30]:
wine_reviews.COUNTRY

0            Italy
1         Portugal
2               US
3               US
4               US
            ...   
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: COUNTRY, Length: 129971, dtype: object

**⚠ Warning!** 
* You can use this access only if the index element is a valid Python identifier, e.g. s.1 is not allowed. See here for an explanation of valid identifiers.
* The attribute will not be available if it conflicts with an existing method name, e.g. s.min is not allowed, but s['min'] is possible.
* Similarly, the attribute will not be available if it conflicts with any of the following list: index, major_axis, minor_axis, items.
* In any of these cases, standard indexing will still work, e.g. s['1'], s['min'], and s['index'] will access the corresponding element or column.

### Getitem ([])
A common way of indexing is by using the square brackets ([]):
* For a Series, a single value is returned.
* For a DataFrame, passing a single label returns a Series corresponding to the column with that label.

In [31]:
wine_reviews['COUNTRY']
type(wine_reviews['COUNTRY'])

0            Italy
1         Portugal
2               US
3               US
4               US
            ...   
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: COUNTRY, Length: 129971, dtype: object

pandas.core.series.Series

To retrieve a single value, we need to use the indexing operator `[]` once more:

In [32]:
wine_reviews['COUNTRY'][0]

'Italy'

You can pass a list of columns to [] to select columns in that order. In this case, a DataFrame is returned:

In [33]:
# retrieve multiple columns as a DataFrame
wine_reviews[['COUNTRY','PRICE']]
type(wine_reviews[['COUNTRY','PRICE']])

COUNTRY  PRICE
0          Italy    NaN
1       Portugal   15.0
2             US   14.0
3             US   13.0
4             US   65.0
...          ...    ...
129966   Germany   28.0
129967        US   75.0
129968    France   30.0
129969    France   32.0
129970    France   21.0

[129971 rows x 2 columns]

pandas.core.frame.DataFrame

### Slicing ranges ([:])
* With **Series**, the syntax works **exactly as with an ndarray**, returning a slice of the values and the corresponding labels
* With **DataFrame**, slicing inside of **[] slices the rows**. This is provided largely as a convenience since it is such a common operation.

In [34]:
# slicing a Series
wine_reviews['COUNTRY'][3:9]

3         US
4         US
5      Spain
6      Italy
7     France
8    Germany
Name: COUNTRY, dtype: object

In [35]:
# slicing a DataFrame
wine_reviews[3:9]

COUNTRY                                        DESCRIPTION  \
3       US  Pineapple rind, lemon pith and orange blossom ...   
4       US  Much like the regular bottling from 2012, this...   
5    Spain  Blackberry and raspberry aromas show a typical...   
6    Italy  Here's a bright, informal red that opens with ...   
7   France  This dry and restrained wine offers spice in p...   
8  Germany  Savory dried thyme notes accent sunnier flavor...   

                          DESIGNATION  POINTS  PRICE           PROVINCE  \
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   
5                        Ars In Vitro      87   15.0     Northern Spain   
6                             Belsito      87   16.0  Sicily & Sardinia   
7                                 NaN      87   24.0             Alsace   
8                               Shine      87   12.0        Rheinhessen   

              REGION_1           REGION_2         TASTER_NAME  \
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   
5              Navarra                NaN   Michael Schachner   
6             Vittoria                NaN       Kerin O’Keefe   
7               Alsace                NaN          Roger Voss   
8                  NaN                NaN  Anna Lee C. Iijima   

  TASTER_TWITTER_HANDLE                                              TITLE  \
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   
5           @wineschach  Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...   
6          @kerinokeefe   Terre di Giurfo 2013 Belsito Frappato (Vittoria)   
7            @vossroger              Trimbach 2012 Gewurztraminer (Alsace)   
8                   NaN  Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...   

              VARIETY           WINERY  
3            Riesling       St. Julian  
4          Pinot Noir     Sweet Cheeks  
5  Tempranillo-Merlot           Tandem  
6            Frappato  Terre di Giurfo  
7      Gewürztraminer         Trimbach  
8      Gewürztraminer      Heinz Eifel

**❓ How do we select specific rows and columns from a DataFrame?**

### loc and iloc

To **subset both rows and columns in one go just using selection brackets [] is not possible**. The **loc/iloc operators are required in front of the selection brackets []**. When using loc/iloc, the part before the comma is the rows you want, and the part after the comma is the columns you want to select.

#### Selection by position (iloc)

pandas provides a suite of methods in order to get **purely integer based indexing**. **The semantics follow closely Python and NumPy slicing**. These are 0-based indexing. When slicing, the start bound is included, while the upper bound is excluded. Trying to use a non-integer, even a valid label will raise an IndexError.

The .iloc attribute is the primary access method. The following are valid inputs:
* An integer e.g. 5.
* A list or array of integers [4, 3, 0].
* A slice object with ints 1:7.
* A boolean array.
* A callable, see [Selection By Callable](https://pandas.pydata.org/docs/user_guide/indexing.html#selection-by-callable).

In [36]:
# indexing with an integer
wine_reviews.iloc[0]

COUNTRY                                                              Italy
DESCRIPTION              Aromas include tropical fruit, broom, brimston...
DESIGNATION                                                   Vulkà Bianco
POINTS                                                                  87
PRICE                                                                  NaN
PROVINCE                                                 Sicily & Sardinia
REGION_1                                                              Etna
REGION_2                                                               NaN
TASTER_NAME                                                  Kerin O’Keefe
TASTER_TWITTER_HANDLE                                         @kerinokeefe
TITLE                                    Nicosia 2013 Vulkà Bianco  (Etna)
VARIETY                                                        White Blend
WINERY                                                             Nicosia
Name: 0, dtype: object

In [37]:
# indexing the first column
wine_reviews.iloc[:, 0]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...   
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: COUNTRY, Length: 129971, dtype: object

To select the first three rows and the first column we write the following:

In [38]:
wine_reviews.iloc[:3,0]

0       Italy
1    Portugal
2          US
Name: COUNTRY, dtype: object

It's also possible to pass a list:

In [39]:
wine_reviews.iloc[[0,1,2], 0] 

0       Italy
1    Portugal
2          US
Name: COUNTRY, dtype: object

#### Selection by label (loc)

pandas provides a suite of methods in order to have **purely label based indexing**. When slicing, both **the start bound AND the stop bound are included**, if present in the index. **Integers** are valid labels, but they **refer to the label and not the position**.

The .loc attribute is the primary access method. The following are valid inputs:
* A single label, e.g. 5 or 'a' (**Note that 5 is interpreted as a label of the index. This use is not an integer position along the index.**).
* A list or array of labels ['a', 'b', 'c'].
* A slice object with labels 'a':'f' (Note that contrary to usual Python slices, both the start and the stop are included, when present in the index!
* A boolean array.
* A callable.

For example, to get the first entry in `wine_reviews`, we would now do the following:

In [40]:
wine_reviews.loc[0, 'COUNTRY']

'Italy'

Or you can use a list of labels:

In [41]:
wine_reviews.loc[:, ['TASTER_NAME', 'TASTER_TWITTER_HANDLE', 'POINTS']]

TASTER_NAME TASTER_TWITTER_HANDLE  POINTS
0            Kerin O’Keefe          @kerinokeefe      87
1               Roger Voss            @vossroger      87
2             Paul Gregutt           @paulgwine       87
3       Alexander Peartree                   NaN      87
4             Paul Gregutt           @paulgwine       87
...                    ...                   ...     ...
129966  Anna Lee C. Iijima                   NaN      90
129967        Paul Gregutt           @paulgwine       90
129968          Roger Voss            @vossroger      90
129969          Roger Voss            @vossroger      90
129970          Roger Voss            @vossroger      90

[129971 rows x 3 columns]

#### Transitioning between `loc` and `iloc`

When choosing or transitioning between `loc` and `iloc`, there is one "gotcha" worth keeping in mind, which is that the two methods use slightly different indexing schemes.

`iloc` uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So `0:10` will select entries `0,...,9`. `loc`, meanwhile, indexes inclusively. So `0:10` will select entries `0,...,10`.

Why the change? Remember that loc can index any stdlib type: strings, for example. If we have a DataFrame with index values `Apples, ..., Potatoes, ...`, and we want to select "all the alphabetical fruit choices between Apples and Potatoes", then it's a lot more convenient to index `df.loc['Apples':'Potatoes', :]` than it is to index something like `df.loc['Apples':'Potatoet',:]` (`t` coming after `s` in the alphabet).

This is particularly confusing when the DataFrame index is a simple numerical list, e.g. `0,...,1000`. In this case `df.iloc[0:1000]` will return 1000 entries, while `df.loc[0:1000]` return 1001 of them! To get 1000 elements using `loc`, you will need to go one lower and ask for `df.loc[0:999]`. 

Otherwise, the semantics of using `loc` are the same as those for `iloc`.

#### Combining positional and label-based indexing

What if you wish to get the 0th and the 2nd elements from the index in the ‘COUNTRY’ column? You can do:

In [42]:
wine_reviews.loc[wine_reviews.index[[0, 2]], 'COUNTRY']

0    Italy
2       US
Name: COUNTRY, dtype: object

This can also be expressed using .iloc, by explicitly getting locations on the indexers, and using positional indexing to select things:

In [43]:
wine_reviews.iloc[[0, 2], wine_reviews.columns.get_loc('COUNTRY')]

0    Italy
2       US
Name: COUNTRY, dtype: object

### Boolean indexing

So far we've been indexing various strides of data, using structural properties of the DataFrame itself. To do *interesting* things with the data, however, we often need to ask questions based on conditions. 

For example, suppose that we're interested specifically in better-than-average wines produced in Italy.

We can start by checking if each wine is Italian or not:

In [44]:
wine_reviews['COUNTRY'] == 'Italy'

0          True
1         False
2         False
3         False
4         False
          ...  
129966    False
129967    False
129968    False
129969    False
129970    False
Name: COUNTRY, Length: 129971, dtype: bool

This operation produced a Series of `True`/`False` booleans based on the `country` of each record.  This result can then be used inside of `loc` to select the relevant rows:

In [45]:
wine_reviews.loc[wine_reviews['COUNTRY'] == 'Italy']

COUNTRY                                        DESCRIPTION  \
0        Italy  Aromas include tropical fruit, broom, brimston...   
6        Italy  Here's a bright, informal red that opens with ...   
13       Italy  This is dominated by oak and oak-driven aromas...   
22       Italy  Delicate aromas recall white flower and citrus...   
24       Italy  Aromas of prune, blackcurrant, toast and oak c...   
...        ...                                                ...   
129929   Italy  This luminous sparkler has a sweet, fruit-forw...   
129943   Italy  A blend of Nero d'Avola and Syrah, this convey...   
129947   Italy  A blend of 65% Cabernet Sauvignon, 30% Merlot ...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      DESIGNATION  POINTS  PRICE           PROVINCE  \
0                    Vulkà Bianco      87    NaN  Sicily & Sardinia   
6                         Belsito      87   16.0  Sicily & Sardinia   
13                          Rosso      87    NaN  Sicily & Sardinia   
22                      Ficiligno      87   19.0  Sicily & Sardinia   
24                          Aynat      87   35.0  Sicily & Sardinia   
...                           ...     ...    ...                ...   
129929                        NaN      91   38.0             Veneto   
129943                    Adènzia      90   29.0  Sicily & Sardinia   
129947                   Symposio      90   20.0  Sicily & Sardinia   
129961                        NaN      90   30.0  Sicily & Sardinia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia   

                              REGION_1 REGION_2    TASTER_NAME  \
0                                 Etna      NaN  Kerin O’Keefe   
6                             Vittoria      NaN  Kerin O’Keefe   
13                                Etna      NaN  Kerin O’Keefe   
22                             Sicilia      NaN  Kerin O’Keefe   
24                             Sicilia      NaN  Kerin O’Keefe   
...                                ...      ...            ...   
129929  Prosecco Superiore di Cartizze      NaN            NaN   
129943                         Sicilia      NaN  Kerin O’Keefe   
129947                 Terre Siciliane      NaN  Kerin O’Keefe   
129961                         Sicilia      NaN  Kerin O’Keefe   
129962                         Sicilia      NaN  Kerin O’Keefe   

       TASTER_TWITTER_HANDLE  \
0               @kerinokeefe   
6               @kerinokeefe   
13              @kerinokeefe   
22              @kerinokeefe   
24              @kerinokeefe   
...                      ...   
129929                   NaN   
129943          @kerinokeefe   
129947          @kerinokeefe   
129961          @kerinokeefe   
129962          @kerinokeefe   

                                                    TITLE            VARIETY  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)        White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)           Frappato   
13                 Masseria Setteporte 2012 Rosso  (Etna)  Nerello Mascalese   
22      Baglio di Pianetto 2007 Ficiligno White (Sicilia)        White Blend   
24            Canicattì 2009 Aynat Nero d'Avola (Sicilia)       Nero d'Avola   
...                                                   ...                ...   
129929  Col Vetoraz Spumanti NV  Prosecco Superiore di...           Prosecco   
129943  Baglio del Cristo di Campobello 2012 Adènzia R...          Red Blend   
129947  Feudo Principi di Butera 2012 Symposio Red (Te...          Red Blend   
129961                        COS 2013 Frappato (Sicilia)           Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...       Nero d'Avola   

                                 WINERY  
0                               Nicosia  
6                       Terre di Giurfo  
13                  Masseria Setteporte  
22                

This DataFrame has ~20,000 rows. The original had ~130,000. That means that around 15% of wines originate from Italy.

We also wanted to know which ones are better than average. Wines are reviewed on a 80-to-100 point scale. Thus we want wines that accrued at least 90 points.

We can use the ampersand (`&`) to bring the two questions together:

In [46]:
wine_reviews.loc[(wine_reviews['COUNTRY'] == 'Italy') & (wine_reviews['POINTS'] >= 90)]

COUNTRY                                        DESCRIPTION  \
120      Italy  Slightly backward, particularly given the vint...   
130      Italy  At the first it was quite muted and subdued, b...   
133      Italy  Einaudi's wines have been improving lately, an...   
135      Italy  The color is just beginning to show signs of b...   
140      Italy  A big, fat, luscious wine with plenty of toast...   
...        ...                                                ...   
129929   Italy  This luminous sparkler has a sweet, fruit-forw...   
129943   Italy  A blend of Nero d'Avola and Syrah, this convey...   
129947   Italy  A blend of 65% Cabernet Sauvignon, 30% Merlot ...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      DESIGNATION  POINTS  PRICE           PROVINCE  \
120           Bricco Rocche Prapó      92   70.0           Piedmont   
130         Bricco Rocche Brunate      91   70.0           Piedmont   
133                           NaN      91   68.0           Piedmont   
135                        Sorano      91   60.0           Piedmont   
140                   Costa Bruna      90   26.0           Piedmont   
...                           ...     ...    ...                ...   
129929                        NaN      91   38.0             Veneto   
129943                    Adènzia      90   29.0  Sicily & Sardinia   
129947                   Symposio      90   20.0  Sicily & Sardinia   
129961                        NaN      90   30.0  Sicily & Sardinia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia   

                              REGION_1 REGION_2    TASTER_NAME  \
120                             Barolo      NaN            NaN   
130                             Barolo      NaN            NaN   
133                             Barolo      NaN            NaN   
135                             Barolo      NaN            NaN   
140                     Barbera d'Alba      NaN            NaN   
...                                ...      ...            ...   
129929  Prosecco Superiore di Cartizze      NaN            NaN   
129943                         Sicilia      NaN  Kerin O’Keefe   
129947                 Terre Siciliane      NaN  Kerin O’Keefe   
129961                         Sicilia      NaN  Kerin O’Keefe   
129962                         Sicilia      NaN  Kerin O’Keefe   

       TASTER_TWITTER_HANDLE  \
120                      NaN   
130                      NaN   
133                      NaN   
135                      NaN   
140                      NaN   
...                      ...   
129929                   NaN   
129943          @kerinokeefe   
129947          @kerinokeefe   
129961          @kerinokeefe   
129962          @kerinokeefe   

                                                    TITLE       VARIETY  \
120            Ceretto 2003 Bricco Rocche Prapó  (Barolo)      Nebbiolo   
130          Ceretto 2003 Bricco Rocche Brunate  (Barolo)      Nebbiolo   
133                     Poderi Luigi Einaudi 2003  Barolo      Nebbiolo   
135                 Giacomo Ascheri 2001 Sorano  (Barolo)      Nebbiolo   
140       Poderi Colla 2005 Costa Bruna  (Barbera d'Alba)       Barbera   
...                                                   ...           ...   
129929  Col Vetoraz Spumanti NV  Prosecco Superiore di...      Prosecco   
129943  Baglio del Cristo di Campobello 2012 Adènzia R...     Red Blend   
129947  Feudo Principi di Butera 2012 Symposio Red (Te...     Red Blend   
129961                        COS 2013 Frappato (Sicilia)      Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...  Nero d'Avola   

                                 WINERY  
120                             Ceretto  
130                             Ceretto  
133                Poderi Luigi Einaudi  
135                     Giacomo Ascheri  
140                        Poderi Co

Suppose we'll buy any wine that's made in Italy _or_ which is rated above average. For this we use a pipe (`|`):

In [47]:
wine_reviews.loc[(wine_reviews['COUNTRY'] == 'Italy') | (wine_reviews['POINTS'] >= 90)]

COUNTRY                                        DESCRIPTION  \
0         Italy  Aromas include tropical fruit, broom, brimston...   
6         Italy  Here's a bright, informal red that opens with ...   
13        Italy  This is dominated by oak and oak-driven aromas...   
22        Italy  Delicate aromas recall white flower and citrus...   
24        Italy  Aromas of prune, blackcurrant, toast and oak c...   
...         ...                                                ...   
129966  Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967       US  Citation is given as much as a decade of bottl...   
129968   France  Well-drained gravel soil gives this wine its c...   
129969   France  A dry style of Pinot Gris, this is crisp with ...   
129970   France  Big, rich and off-dry, this is powered by inte...   

                                   DESIGNATION  POINTS  PRICE  \
0                                 Vulkà Bianco      87    NaN   
6                                      Belsito      87   16.0   
13                                       Rosso      87    NaN   
22                                   Ficiligno      87   19.0   
24                                       Aynat      87   35.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 PROVINCE  REGION_1      REGION_2         TASTER_NAME  \
0       Sicily & Sardinia      Etna           NaN       Kerin O’Keefe   
6       Sicily & Sardinia  Vittoria           NaN       Kerin O’Keefe   
13      Sicily & Sardinia      Etna           NaN       Kerin O’Keefe   
22      Sicily & Sardinia   Sicilia           NaN       Kerin O’Keefe   
24      Sicily & Sardinia   Sicilia           NaN       Kerin O’Keefe   
...                   ...       ...           ...                 ...   
129966              Mosel       NaN           NaN  Anna Lee C. Iijima   
129967             Oregon    Oregon  Oregon Other        Paul Gregutt   
129968             Alsace    Alsace           NaN          Roger Voss   
129969             Alsace    Alsace           NaN          Roger Voss   
129970             Alsace    Alsace           NaN          Roger Voss   

       TASTER_TWITTER_HANDLE  \
0               @kerinokeefe   
6               @kerinokeefe   
13              @kerinokeefe   
22              @kerinokeefe   
24              @kerinokeefe   
...                      ...   
129966                   NaN   
129967           @paulgwine    
129968            @vossroger   
129969            @vossroger   
129970            @vossroger   

                                                    TITLE            VARIETY  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)        White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)           Frappato   
13                 Masseria Setteporte 2012 Rosso  (Etna)  Nerello Mascalese   
22      Baglio di Pianetto 2007 Ficiligno White (Sicilia)        White Blend   
24            Canicattì 2009 Aynat Nero d'Avola (Sicilia)       Nero d'Avola   
...                                                   ...                ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...           Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)         Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...     Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)         Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...     Gewürztraminer   

                                          WINERY  
0                                        Nicosia  
6                                Terre di Giurfo  
13        

The operators to use for boolean vectors are: **|** for **or**, **&** for **and**, and **~** for **not**. These must be **grouped by using parentheses**, since by default Python will evaluate an expression such as `df['A'] > 2 & df['B'] < 3` as `df['A'] > (2 & df['B']) < 3`, while the desired evaluation order is `(df['A'] > 2) & (df['B'] < 3)`.

### Indexing with isin
Consider the `isin()` method of Series, which returns a boolean vector that is true wherever the Series elements exist in the passed list. This allows you to select rows where one or more columns have values you want.

For example, here's how we can use it to select wines only from Italy or France:

In [48]:
wine_reviews.loc[wine_reviews['COUNTRY'].isin(['Italy', 'France'])]

COUNTRY                                        DESCRIPTION  \
0        Italy  Aromas include tropical fruit, broom, brimston...   
6        Italy  Here's a bright, informal red that opens with ...   
7       France  This dry and restrained wine offers spice in p...   
9       France  This has great depth of flavor with its fresh ...   
11      France  This is a dry wine, very spicy, with a tight, ...   
...        ...                                                ...   
129964  France  Initially quite muted, this wine slowly develo...   
129965  France  While it's rich, this beautiful dry wine also ...   
129968  France  Well-drained gravel soil gives this wine its c...   
129969  France  A dry style of Pinot Gris, this is crisp with ...   
129970  France  Big, rich and off-dry, this is powered by inte...   

                          DESIGNATION  POINTS  PRICE           PROVINCE  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
6                             Belsito      87   16.0  Sicily & Sardinia   
7                                 NaN      87   24.0             Alsace   
9                         Les Natures      87   27.0             Alsace   
11                                NaN      87   30.0             Alsace   
...                               ...     ...    ...                ...   
129964   Domaine Saint-Rémy Herrenweg      90    NaN             Alsace   
129965    Seppi Landmann Vallée Noble      90   28.0             Alsace   
129968                          Kritt      90   30.0             Alsace   
129969                            NaN      90   32.0             Alsace   
129970  Lieu-dit Harth Cuvée Caroline      90   21.0             Alsace   

        REGION_1 REGION_2    TASTER_NAME TASTER_TWITTER_HANDLE  \
0           Etna      NaN  Kerin O’Keefe          @kerinokeefe   
6       Vittoria      NaN  Kerin O’Keefe          @kerinokeefe   
7         Alsace      NaN     Roger Voss            @vossroger   
9         Alsace      NaN     Roger Voss            @vossroger   
11        Alsace      NaN     Roger Voss            @vossroger   
...          ...      ...            ...                   ...   
129964    Alsace      NaN     Roger Voss            @vossroger   
129965    Alsace      NaN     Roger Voss            @vossroger   
129968    Alsace      NaN     Roger Voss            @vossroger   
129969    Alsace      NaN     Roger Voss            @vossroger   
129970    Alsace      NaN     Roger Voss            @vossroger   

                                                    TITLE         VARIETY  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)        Frappato   
7                   Trimbach 2012 Gewurztraminer (Alsace)  Gewürztraminer   
9       Jean-Baptiste Adam 2012 Les Natures Pinot Gris...      Pinot Gris   
11                Leon Beyer 2012 Gewurztraminer (Alsace)  Gewürztraminer   
...                                                   ...             ...   
129964  Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...  Gewürztraminer   
129965  Domaine Rieflé-Landmann 2013 Seppi Landmann Va...      Pinot Gris   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                         WINERY  
0                       Nicosia  
6               Terre di Giurfo  
7                      Trimbach  
9            Jean-Baptiste Adam  
11                   Leon Beyer  
...                         ...  
129964          Domaine Ehrhart  
129965  Domaine Rieflé-Landmann  
129968          Domaine Gresser  
129969     Domaine Marcel Deiss  
129970         Domaine Schoffit  

[41633 rows x 13 columns]

You can also use the `isnull` method (and its companion `notnull`). These methods let you highlight values which are (or are not) empty (`NaN`). For example, to filter out wines lacking a price tag in the dataset, here's what we would do:

In [49]:
wine_reviews.loc[wine_reviews['PRICE'].notnull()]

COUNTRY                                        DESCRIPTION  \
1       Portugal  This is ripe and fruity, a wine that is smooth...   
2             US  Tart and snappy, the flavors of lime flesh and...   
3             US  Pineapple rind, lemon pith and orange blossom ...   
4             US  Much like the regular bottling from 2012, this...   
5          Spain  Blackberry and raspberry aromas show a typical...   
...          ...                                                ...   
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967        US  Citation is given as much as a decade of bottl...   
129968    France  Well-drained gravel soil gives this wine its c...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                                   DESIGNATION  POINTS  PRICE        PROVINCE  \
1                                     Avidagos      87   15.0           Douro   
2                                          NaN      87   14.0          Oregon   
3                         Reserve Late Harvest      87   13.0        Michigan   
4           Vintner's Reserve Wild Child Block      87   65.0          Oregon   
5                                 Ars In Vitro      87   15.0  Northern Spain   
...                                        ...     ...    ...             ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0           Mosel   
129967                                     NaN      90   75.0          Oregon   
129968                                   Kritt      90   30.0          Alsace   
129969                                     NaN      90   32.0          Alsace   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0          Alsace   

                   REGION_1           REGION_2         TASTER_NAME  \
1                       NaN                NaN          Roger Voss   
2         Willamette Valley  Willamette Valley        Paul Gregutt   
3       Lake Michigan Shore                NaN  Alexander Peartree   
4         Willamette Valley  Willamette Valley        Paul Gregutt   
5                   Navarra                NaN   Michael Schachner   
...                     ...                ...                 ...   
129966                  NaN                NaN  Anna Lee C. Iijima   
129967               Oregon       Oregon Other        Paul Gregutt   
129968               Alsace                NaN          Roger Voss   
129969               Alsace                NaN          Roger Voss   
129970               Alsace                NaN          Roger Voss   

       TASTER_TWITTER_HANDLE  \
1                 @vossroger   
2                @paulgwine    
3                        NaN   
4                @paulgwine    
5                @wineschach   
...                      ...   
129966                   NaN   
129967           @paulgwine    
129968            @vossroger   
129969            @vossroger   
129970            @vossroger   

                                                    TITLE             VARIETY  \
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)      Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)          Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...            Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...          Pinot Noir   
5       Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...  Tempranillo-Merlot   
...                                                   ...                 ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...            Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)          Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...      Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)          Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...      Gew

<a id='assigning_data'></a>
## Assigning data

Assigning data to a DataFrame is easy. You can assign either a constant value:

In [50]:
wine_reviews['CRITIC'] = 'everyone'
wine_reviews['CRITIC']

0         everyone
1         everyone
2         everyone
3         everyone
4         everyone
            ...   
129966    everyone
129967    everyone
129968    everyone
129969    everyone
129970    everyone
Name: CRITIC, Length: 129971, dtype: object

Or with an iterable of values:

In [51]:
wine_reviews['INDEX_REVERSED'] = range(len(wine_reviews), 0, -1)
wine_reviews['INDEX_REVERSED']

0         129971
1         129970
2         129969
3         129968
4         129967
           ...  
129966         5
129967         4
129968         3
129969         2
129970         1
Name: INDEX_REVERSED, Length: 129971, dtype: int64

Or assign values to specific cells/columns/rows with indexing (`loc`, `iloc`, boolean indexing, etc.):

In [52]:
wine_reviews['POINTS'].min()
wine_reviews[wine_reviews['POINTS'] < 85] = 85
wine_reviews['POINTS'].min()

80

85

<a id='adding_deleting_columns'></a>
## Adding and deleting columns

You can treat a `DataFrame` semantically like a dict of like-indexed `Series` objects. Getting, setting, and deleting columns works with the same syntax as the analogous dict operations.

### Add a column

In [53]:
cities['population (M)'] = cities['population'] / 1000000
cities

name  population    area position  population (M)
0      California    39512223  423967     West       39.512223
1      Washington     7614893  184661     West        7.614893
2        New York    19453561  141297      Est       19.453561
3  North Carolina    10488084  139391      Est       10.488084
4         Florida    21477737  170312      Est       21.477737

By default, columns get inserted at the end. `DataFrame.insert()` inserts at a particular location in the columns:

In [54]:
pop_density = cities['population'] / cities['area']
cities.insert(3, "population density", pop_density)
cities

name  population    area  population density position  \
0      California    39512223  423967           93.196459     West   
1      Washington     7614893  184661           41.237148     West   
2        New York    19453561  141297          137.678514      Est   
3  North Carolina    10488084  139391           75.242189      Est   
4         Florida    21477737  170312          126.108184      Est   

   population (M)  
0       39.512223  
1        7.614893  
2       19.453561  
3       10.488084  
4       21.477737

We can create a new boolean column to flag the high-density cities:

In [55]:
cities['high-density'] = cities['population density'] > 100.0
cities

name  population    area  population density position  \
0      California    39512223  423967           93.196459     West   
1      Washington     7614893  184661           41.237148     West   
2        New York    19453561  141297          137.678514      Est   
3  North Carolina    10488084  139391           75.242189      Est   
4         Florida    21477737  170312          126.108184      Est   

   population (M)  high-density  
0       39.512223         False  
1        7.614893         False  
2       19.453561          True  
3       10.488084         False  
4       21.477737          True

### Delete a column

In [56]:
cities.drop('population (M)', axis=1)

name  population    area  population density position  \
0      California    39512223  423967           93.196459     West   
1      Washington     7614893  184661           41.237148     West   
2        New York    19453561  141297          137.678514      Est   
3  North Carolina    10488084  139391           75.242189      Est   
4         Florida    21477737  170312          126.108184      Est   

   high-density  
0         False  
1         False  
2          True  
3         False  
4          True

In [57]:
# the original dataframe has not been modified yet
cities

name  population    area  population density position  \
0      California    39512223  423967           93.196459     West   
1      Washington     7614893  184661           41.237148     West   
2        New York    19453561  141297          137.678514      Est   
3  North Carolina    10488084  139391           75.242189      Est   
4         Florida    21477737  170312          126.108184      Est   

   population (M)  high-density  
0       39.512223         False  
1        7.614893         False  
2       19.453561          True  
3       10.488084         False  
4       21.477737          True

In [58]:
# solution 1) reassign the variable value
cities = cities.drop('population (M)', axis=1)
cities

name  population    area  population density position  \
0      California    39512223  423967           93.196459     West   
1      Washington     7614893  184661           41.237148     West   
2        New York    19453561  141297          137.678514      Est   
3  North Carolina    10488084  139391           75.242189      Est   
4         Florida    21477737  170312          126.108184      Est   

   high-density  
0         False  
1         False  
2          True  
3         False  
4          True

In [59]:
# solution 2) set the inplace parameter to True
cities.drop('population density', axis=1, inplace=True)
cities

name  population    area position  high-density
0      California    39512223  423967     West         False
1      Washington     7614893  184661     West         False
2        New York    19453561  141297      Est          True
3  North Carolina    10488084  139391      Est         False
4         Florida    21477737  170312      Est          True

<a id='grouping'></a>
## Grouping

Often we want to group our data, and then do something specific to the group the data is in. 

We do this with the `groupby()` method. 

One function we've already seen is the `value_counts()` function. It is used to see a list of unique values and how often they occur in the dataset. We can replicate what `value_counts()` does by doing the following:

In [60]:
wine_reviews.groupby('POINTS')['POINTS'].count()

POINTS
85     21960
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: POINTS, dtype: int64

`groupby()` created a group of reviews which allotted the same point values to the given wines. Then, for each of these groups, we grabbed the 'POINTS' column and counted how many times it appeared.  `value_counts()` is just a shortcut to this `groupby()` operation. 

We can use any of the summary functions we've used before with this data. For example, to get the cheapest wine in each point value category, we can do the following:

In [61]:
wine_reviews.groupby('POINTS')['PRICE'].min()

POINTS
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: PRICE, dtype: float64

For even more fine-grained control, you can also group by more than one column. For an example, here's how we compute the mean of points for each country and province:

In [62]:
wine_reviews.groupby(['COUNTRY', 'PROVINCE'])['POINTS'].mean()

COUNTRY    PROVINCE        
85         85                  85.000000
Argentina  Mendoza Province    88.229814
           Other               87.368280
Armenia    Armenia             87.500000
Australia  Australia Other     86.616766
                                 ...    
Uruguay    Juanico             88.500000
           Montevideo          88.800000
           Progreso            87.666667
           San Jose            87.000000
           Uruguay             87.650000
Name: POINTS, Length: 413, dtype: float64

🤓 For more detailed information, [read here](https://pandas.pydata.org/docs/user_guide/groupby.html)

<a id='merging'></a>
## Merging

In Pandas, `merge`, `join`, and `concat` are three different methods used for combining and merging data, but they have distinct use cases and behavior.
In summary:
- Use `merge` when you want to perform a more complex operation, such as combining DataFrames based on common columns or indices.
- Use `join` when you want to combine DataFrames based on their indices.
- Use `concat` when you want to concatenate DataFrames along a specific axis.

### Merge
`merge` is a powerful method for combining two DataFrames based on common columns or indices.
- It allows you to specify the columns on which the merging should occur, similar to SQL joins (e.g., inner, outer, left, right joins).
- You can merge DataFrames based on one or more key columns and control the behavior of the merge, such as handling duplicates, specifying the type of join, and handling missing values.

   Example:
   ```python
   result = pd.merge(df1, df2, on='common_column', how='inner')
   ```

![join_diagram](https://files.realpython.com/media/join_diagram.93e6ef63afbe.png)

#### Importing Data
These two datasets are from the [National Oceanic and Atmospheric Administration (NOAA)](https://www.ncdc.noaa.gov/cdo-web/) and were derived from the NOAA public data repository. The following examples are from the [Real Python website.](https://realpython.com/pandas-merge-join-and-concat)

In [67]:
climate_temp = pd.read_csv("data/climate_temp.csv")
climate_temp.head()

STATION            STATION_NAME ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  ...  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  DLY-CLDD-BASE72  \
0            -7777  ...                0                0                0   
1            -7777  ...                0                0                0   
2            -7777  ...                0                0                0   
3            -7777  ...                0                0                0   
4            -7777  ...                0                0                0   

   DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  DLY-HTDD-BASE55  \
0            -7777                1                2                6   
1            -7777                1                2                6   
2            -7777                1                2                5   
3            -7777                1                2                5   
4            -7777            -7777                2                5   

   DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  
0                7               10               15  
1                7               10               15  
2                7               10               15  
3                7               10               15  
4                7               10               15  

[5 rows x 21 columns]

In [68]:
climate_temp.shape

(127020, 21)

In [70]:
climate_precip = pd.read_csv("data/climate_precip.csv")
climate_precip.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100101            -6.66   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100102            -6.66   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100103            -6.66   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100104            -6.66   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100105            -6.66   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0             -666            -66.6            -6.66             -666   
1             -666            -66.6            -6.66             -666   
2             -666            -66.6            -6.66             -666   
3            -9999          -9999.0            -6.66            -9999   
4            -9999          -9999.0            -6.66            -9999   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-PRCP-PCTALL-GE100HI  \
0            -66.6            -6.66  ...                        3   
1            -66.6            -6.66  ...                        3   
2            -66.6            -6.66  ...                        3   
3          -9999.0            -6.66  ...                        3   
4          -9999.0            -6.66  ...                        3   

   DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  DLY-SNWD-PCTALL-GE003WI  \
0                    -9999                        0                    -9999   
1                    -9999                        0                    -9999   
2                    -9999                        0                    -9999   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  \
0                    -9999                    -9999                    -9999   
1                    -9999                    -9999                    -9999   
2                    -9999                    -9999                    -9999   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  DLY-SNOW-PCTALL-GE050TI  
0                        0                    -9999                    -9999  
1                        0                    -9999                    -9999  
2                        0                    -9999                    -9999  
3                        0                        0                        0  
4                        0                        0                        0  

[5 rows x 29 columns]

In [71]:
climate_precip.shape

(151110, 29)

#### Inner Join

Here, you will use a plain `merge()` call to do an inner join and learn how this can result in a smaller, more focused dataset. First, you will create a new DataFrame object that contains the precipitation data from one station.

In [72]:
precip_one_station = climate_precip.query("STATION == 'GHCND:USC00045721'")
precip_one_station.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
1460  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1461  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
1462  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
1463  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
1464  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1460             -666            -66.6             0.16             -666   
1461             -666            -66.6             0.16             -666   
1462             -666            -66.6             0.16             -666   
1463             -666            -66.6             0.16             -666   
1464             -666            -66.6             0.17             -666   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-PRCP-PCTALL-GE100HI  \
1460            -66.6             0.44  ...                       11   
1461            -66.6             0.44  ...                       11   
1462            -66.6             0.45  ...                       11   
1463            -66.6             0.45  ...                       11   
1464            -66.6             0.46  ...                       11   

      DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
1460                        4                        0   
1461                        4                        0   
1462                        4                        0   
1463                        4                        0   
1464                        4                        0   

      DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
1460                        3                        3   
1461                        3                        3   
1462                        3                        3   
1463                        3                        2   
1464                        3                        2   

      DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  \
1460                        9                        6   
1461                       10                        6   
1462                       10                        6   
1463                       10                        6   
1464                       10                        6   

      DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
1460                        0                    -9999   
1461                        0                    -9999   
1462                        0                    -9999   
1463                        0                    -9999   
1464                        0                    -9999   

      DLY-SNOW-PCTALL-GE050TI  
1460                    -9999  
1461                    -9999  
1462                    -9999  
1463                    -9999  
1464                    -9999  

[5 rows x 29 columns]

In [73]:
precip_one_station.shape

(365, 29)

In [74]:
inner_merged = pd.merge(precip_one_station, climate_temp)
inner_merged.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0             -666            -66.6             0.16             -666   
1             -666            -66.6             0.16             -666   
2             -666            -66.6             0.16             -666   
3             -666            -66.6             0.16             -666   
4             -666            -66.6             0.17             -666   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0            -66.6             0.44  ...                0                0   
1            -66.6             0.44  ...                0                0   
2            -66.6             0.45  ...                0                0   
3            -66.6             0.45  ...                0                0   
4            -66.6             0.46  ...                0                0   

   DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
0                0                1                3                6   
1                0                1                3                6   
2                0                1                2                5   
3                0                1                2                5   
4                0                1                2                5   

   DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  
0               10               12               14               19  
1               10               11               14               19  
2                9               11               14               19  
3                9               11               14               19  
4                9               11               14               19  

[5 rows x 47 columns]

How many rows do you think this merged DataFrame has?

In [75]:
inner_merged.shape

(365, 47)

You get 365 rows because any non-matching rows are discarded in an inner join, which is the default merge method for a `merge()` call, and `precip_one_station` had only 365 rows.

What if you want to merge both full datasets, but specify which columns to join on? In this case, you will use the `on` parameter:

In [76]:
inner_merged_total = pd.merge(
    climate_temp, climate_precip, on=["STATION", "DATE"]
)
inner_merged_total.head()

STATION          STATION_NAME_x ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  \
0            -7777  ...                        3                    -9999   
1            -7777  ...                        3                    -9999   
2            -7777  ...                        3                    -9999   
3            -7777  ...                        3                        0   
4            -7777  ...                        3                        0   

   DLY-SNWD-PCTALL-GE010WI  DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
0                        0                    -9999                    -9999   
1                        0                    -9999                    -9999   
2                        0                    -9999                    -9999   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  \
0                    -9999                    -9999                        0   
1                    -9999                    -9999                        0   
2                    -9999                    -9999                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE030TI  DLY-SNOW-PCTALL-GE050TI  
0                    -9999                    -9999  
1                    -9999                    -9999  
2                    -9999                    -9999  
3                        0                        0  
4                        0                        0  

[5 rows x 48 columns]

In [77]:
inner_merged_total.shape

(123005, 48)

You can specify a single _key column_ with a string, or multiple key columns with a list, as in the above example. This results in a DataFrame with 123005 rows and 48 columns. 

Why 48 columns instead of 47? Because you specified the keys columns to join on, Pandas doesn't try to merge all mergeable columns. This can result in "duplicate" column names, which may or may not have different values. "Duplicate" is in quotes because the columns will actually have new names, by default they are appended with `_x` and `_y`. You can also use the `suffixes` parameter to control what is appended to the column names.

#### Outer Join
With the outer join, you will retain rows that don't have matches as well. For this example, you will use the smaller precipitation DataFrame `precip_one_station` with the full `climate_temp` DataFrame and join with `STATION` and `DATE` columns as the key columns. Take a second and think about how many rows you expect the new DataFrame to have.

In [78]:
outer_merged = pd.merge(
    precip_one_station, climate_temp, how="outer", on=["STATION", "DATE"]
)
outer_merged.head()

STATION          STATION_NAME_x      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0           -666.0            -66.6             0.16           -666.0   
1           -666.0            -66.6             0.16           -666.0   
2           -666.0            -66.6             0.16           -666.0   
3           -666.0            -66.6             0.16           -666.0   
4           -666.0            -66.6             0.17           -666.0   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0            -66.6             0.44  ...                0                0   
1            -66.6             0.44  ...                0                0   
2            -66.6             0.45  ...                0                0   
3            -66.6             0.45  ...                0                0   
4            -66.6             0.46  ...                0                0   

   DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
0                0                1                3                6   
1                0                1                3                6   
2                0                1                2                5   
3                0                1                2                5   
4                0                1                2                5   

   DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  
0               10               12               14               19  
1               10               11               14               19  
2                9               11               14               19  
3                9               11               14               19  
4                9               11               14               19  

[5 rows x 48 columns]

In [79]:
outer_merged.shape

(127020, 48)

If you remember from when you checked the `.shape` attribute of `climate_temp`, you'll see that the number of rows in `outer_merged` matches that. With an outer join, you can expect to have the same number of rows as the larger DataFrame, since none are lost like they are in an inner join. 

#### Left Join
Also known as a left outer join. In this join, you will retain rows that don't have matches only on the left (or first) DataFrame to be merged.

In [80]:
left_merged = pd.merge(
    climate_temp, precip_one_station, how="left", on=["STATION", "DATE"]
)
left_merged.head()

STATION          STATION_NAME_x ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  \
0            -7777  ...                      NaN                      NaN   
1            -7777  ...                      NaN                      NaN   
2            -7777  ...                      NaN                      NaN   
3            -7777  ...                      NaN                      NaN   
4            -7777  ...                      NaN                      NaN   

   DLY-SNWD-PCTALL-GE010WI  DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
0                      NaN                      NaN                      NaN   
1                      NaN                      NaN                      NaN   
2                      NaN                      NaN                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                      NaN                      NaN   

   DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  \
0                      NaN                      NaN                      NaN   
1                      NaN                      NaN                      NaN   
2                      NaN                      NaN                      NaN   
3                      NaN                      NaN                      NaN   
4                      NaN                      NaN                      NaN   

   DLY-SNOW-PCTALL-GE030TI  DLY-SNOW-PCTALL-GE050TI  
0                      NaN                      NaN  
1                      NaN                      NaN  
2                      NaN                      NaN  
3                      NaN                      NaN  
4                      NaN                      NaN  

[5 rows x 48 columns]

In [81]:
left_merged.shape

(127020, 48)

Here, you see that the number of rows in the resulting DataFrame matches that of the rows in the `climate_temp` DataFrame. What if we switched the positions of the two DataFrames that we are merging?

In [82]:
left_merged_reversed = pd.merge(
    precip_one_station, climate_temp, how="left", on=["STATION", "DATE"]
)
left_merged_reversed.head()

STATION          STATION_NAME_x      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0             -666            -66.6             0.16             -666   
1             -666            -66.6             0.16             -666   
2             -666            -66.6             0.16             -666   
3             -666            -66.6             0.16             -666   
4             -666            -66.6             0.17             -666   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0            -66.6             0.44  ...                0                0   
1            -66.6             0.44  ...                0                0   
2            -66.6             0.45  ...                0                0   
3            -66.6             0.45  ...                0                0   
4            -66.6             0.46  ...                0                0   

   DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
0                0                1                3                6   
1                0                1                3                6   
2                0                1                2                5   
3                0                1                2                5   
4                0                1                2                5   

   DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  
0               10               12               14               19  
1               10               11               14               19  
2                9               11               14               19  
3                9               11               14               19  
4                9               11               14               19  

[5 rows x 48 columns]

In [83]:
left_merged_reversed.shape

(365, 48)

#### Right Join
This works the same as the left join, however non-matching rows are only retained in the _right_ DataFrame. In the next example, you will recreate the `left_merged` DataFrame but with a right join.

In [84]:
right_merged = pd.merge(
    precip_one_station, climate_temp, how="right", on=["STATION", "DATE"]
)
right_merged.head()

STATION STATION_NAME_x      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00049099            NaN  20100101              NaN   
1  GHCND:USC00049099            NaN  20100102              NaN   
2  GHCND:USC00049099            NaN  20100103              NaN   
3  GHCND:USC00049099            NaN  20100104              NaN   
4  GHCND:USC00049099            NaN  20100105              NaN   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0              NaN              NaN              NaN              NaN   
1              NaN              NaN              NaN              NaN   
2              NaN              NaN              NaN              NaN   
3              NaN              NaN              NaN              NaN   
4              NaN              NaN              NaN              NaN   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0              NaN              NaN  ...                0                0   
1              NaN              NaN  ...                0                0   
2              NaN              NaN  ...                0                0   
3              NaN              NaN  ...                0                0   
4              NaN              NaN  ...                0                0   

   DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
0                0            -7777                1                2   
1                0            -7777                1                2   
2                0            -7777                1                2   
3                0            -7777                1                2   
4                0            -7777            -7777                2   

   DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  
0                6                7               10               15  
1                6                7               10               15  
2                5                7               10               15  
3                5                7               10               15  
4                5                7               10               15  

[5 rows x 48 columns]

In [85]:
right_merged.shape

(127020, 48)

Here, you simply flipped the positions of the input DataFrames and specified a right join. When you inspect `right_merged`, you might notice that it's not exactly the same as `left_merged`. The only difference between the two is the order of the columns: the first input's columns will always be the first in the newly formed DataFrame.

### Join
   - `join` is a method available on DataFrame objects in Pandas.
   - It is used for combining the columns of two potentially differently-indexed DataFrames into a single DataFrame.
   - The join operation is based on the index of the DataFrames. You specify the other DataFrame to join with, and the join operation is performed on the index of both DataFrames.
   - It supports different types of joins, such as inner, outer, left, and right.

   Example:
   ```python
   result = df1.join(df2, how='inner')
   ```

`.join()` uses `merge()` under the hood, but provides a much more simplified interface to `merge()` and by default joins on indexes. Here is an introductory example using the `lsuffix` and `rsuffix` parameters to handle overlapping column names.

In [86]:
precip_one_station.join(climate_temp, lsuffix="_left", rsuffix="_right")

STATION_left       STATION_NAME_left  DATE_left  DLY-PRCP-25PCTL  \
1460  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100101             0.04   
1461  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100102             0.05   
1462  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100103             0.05   
1463  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100104             0.05   
1464  GHCND:USC00045721  MITCHELL CAVERNS CA US   20100105             0.05   
...                 ...                     ...        ...              ...   
1820  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101227             0.04   
1821  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101228             0.04   
1822  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101229             0.04   
1823  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101230             0.04   
1824  GHCND:USC00045721  MITCHELL CAVERNS CA US   20101231             0.04   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1460             -666            -66.6             0.16             -666   
1461             -666            -66.6             0.16             -666   
1462             -666            -66.6             0.16             -666   
1463             -666            -66.6             0.16             -666   
1464             -666            -66.6             0.17             -666   
...               ...              ...              ...              ...   
1820             -666            -66.6             0.15             -666   
1821             -666            -66.6             0.15             -666   
1822             -666            -66.6             0.15             -666   
1823             -666            -66.6             0.15             -666   
1824             -666            -66.6             0.15             -666   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
1460            -66.6             0.44  ...                0                0   
1461            -66.6             0.44  ...                0                0   
1462            -66.6             0.45  ...                0                0   
1463            -66.6             0.45  ...                0                0   
1464            -66.6             0.46  ...                0                0   
...               ...              ...  ...              ...              ...   
1820            -66.6             0.44  ...            -7777                0   
1821            -66.6             0.43  ...            -7777                0   
1822            -66.6             0.43  ...            -7777                0   
1823            -66.6             0.43  ...            -7777                0   
1824            -66.6             0.44  ...            -7777                0   

      DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
1460                0                1                3                6   
1461                0                1                3                6   
1462                0                1                2                5   
1463                0                1                2                5   
1464                0                1                2                5   
...               ...              ...              ...              ...   
1820                0                1                3                6   
1821                0                1                3                6   
1822                0                1                3                6   
1823                0                1                3                6   
1824                0                1                3                6   

      DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  
1460               10               12               14               19  
1461               10               11               14               19  
1462                9               11

If you inspect the data, you'll see that overlapping columns are kept, just renamed to be unique. If we flip this around and instead call `.join()` on the larger DataFrame, you'll notice that the DataFrame is larger, but data that doesn't exist in the smaller DataFrame (`precip_one_station`) is filled in with `NaN` (_Not a Number_) values.

In [87]:
climate_temp.join(precip_one_station, lsuffix="_left", rsuffix="_right")

STATION_left       STATION_NAME_left ELEVATION  LATITUDE  \
0       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
1       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
2       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
3       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
4       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
...                   ...                     ...       ...       ...   
127015  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127016  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127017  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127018  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127019  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   

         LONGITUDE  DATE_left  DLY-CLDD-BASE45  DLY-CLDD-BASE50  \
0       -116.03694   20100101                6                2   
1       -116.03694   20100102                6                2   
2       -116.03694   20100103                6                2   
3       -116.03694   20100104                6                2   
4       -116.03694   20100105                6                2   
...            ...        ...              ...              ...   
127015   -118.0711   20101227                4                2   
127016   -118.0711   20101228                4                2   
127017   -118.0711   20101229                4                2   
127018   -118.0711   20101230                4                2   
127019   -118.0711   20101231                4                2   

        DLY-CLDD-BASE55  DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  \
0                 -7777            -7777  ...                      NaN   
1                     1            -7777  ...                      NaN   
2                     1            -7777  ...                      NaN   
3                     1            -7777  ...                      NaN   
4                     1            -7777  ...                      NaN   
...                 ...              ...  ...                      ...   
127015                1            -7777  ...                      NaN   
127016                1            -7777  ...                      NaN   
127017                1            -7777  ...                      NaN   
127018                1            -7777  ...                      NaN   
127019                1            -7777  ...                      NaN   

        DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                           NaN                      NaN   
1                           NaN                      NaN   
2                           NaN                      NaN   
3                           NaN                      NaN   
4                           NaN                      NaN   
...                         ...                      ...   
127015                      NaN                      NaN   
127016                      NaN                      NaN   
127017                      NaN                      NaN   
127018                      NaN                      NaN   
127019                      NaN                      NaN   

        DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
0                           NaN                      NaN   
1                           NaN                      NaN   
2                           NaN                      NaN   
3                           NaN                      NaN   
4                           NaN                      NaN   
...                         ...                      ...   
127015                      NaN                      NaN   
127016                      NaN                      NaN   
127017                      NaN                      NaN   
127018                      NaN                      NaN   
127019                      NaN                      NaN   



If you must use `.join()` and want to merge the columns, you must set them to be indexes first. First take a look at this previously used `merge()` operation:

In [88]:
inner_merged_total = pd.merge(
    climate_temp, climate_precip, on=["STATION", "DATE"]
)
inner_merged_total.head()

STATION          STATION_NAME_x ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  \
0            -7777  ...                        3                    -9999   
1            -7777  ...                        3                    -9999   
2            -7777  ...                        3                    -9999   
3            -7777  ...                        3                        0   
4            -7777  ...                        3                        0   

   DLY-SNWD-PCTALL-GE010WI  DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
0                        0                    -9999                    -9999   
1                        0                    -9999                    -9999   
2                        0                    -9999                    -9999   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  \
0                    -9999                    -9999                        0   
1                    -9999                    -9999                        0   
2                    -9999                    -9999                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE030TI  DLY-SNOW-PCTALL-GE050TI  
0                    -9999                    -9999  
1                    -9999                    -9999  
2                    -9999                    -9999  
3                        0                        0  
4                        0                        0  

[5 rows x 48 columns]

In [89]:
inner_joined_total = climate_temp.join(
    climate_precip.set_index(["STATION", "DATE"]),
    on=["STATION", "DATE"],
    how="inner",
    lsuffix="_x",
    rsuffix="_y",
)
inner_joined_total.head()

STATION          STATION_NAME_x ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  \
0            -7777  ...                        3                    -9999   
1            -7777  ...                        3                    -9999   
2            -7777  ...                        3                    -9999   
3            -7777  ...                        3                        0   
4            -7777  ...                        3                        0   

   DLY-SNWD-PCTALL-GE010WI  DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
0                        0                    -9999                    -9999   
1                        0                    -9999                    -9999   
2                        0                    -9999                    -9999   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  \
0                    -9999                    -9999                        0   
1                    -9999                    -9999                        0   
2                    -9999                    -9999                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE030TI  DLY-SNOW-PCTALL-GE050TI  
0                    -9999                    -9999  
1                    -9999                    -9999  
2                    -9999                    -9999  
3                        0                        0  
4                        0                        0  

[5 rows x 48 columns]

Because `.join()` works on indexes, if we want to recreate `merge()` before, then we must set indexes on the join columns we specify. In this example, you used the `.set_index()` method to set your indexes to the key columns within the join. 

Below you will see an almost-bare `.join()` call. Because there are overlapping columns, you will have to specify a suffix with `lsuffix`, `rsuffix`, or both, but this example will demonstrate the more typical behavior of `.join()`.

In [90]:
climate_temp.join(climate_precip, lsuffix="_left")

STATION_left       STATION_NAME_left ELEVATION  LATITUDE  \
0       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
1       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
2       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
3       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
4       GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
...                   ...                     ...       ...       ...   
127015  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127016  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127017  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127018  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   
127019  GHCND:USC00046006  MOUNT WILSON CBS CA US    1740.4   34.2308   

         LONGITUDE  DATE_left  DLY-CLDD-BASE45  DLY-CLDD-BASE50  \
0       -116.03694   20100101                6                2   
1       -116.03694   20100102                6                2   
2       -116.03694   20100103                6                2   
3       -116.03694   20100104                6                2   
4       -116.03694   20100105                6                2   
...            ...        ...              ...              ...   
127015   -118.0711   20101227                4                2   
127016   -118.0711   20101228                4                2   
127017   -118.0711   20101229                4                2   
127018   -118.0711   20101230                4                2   
127019   -118.0711   20101231                4                2   

        DLY-CLDD-BASE55  DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  \
0                 -7777            -7777  ...                        3   
1                     1            -7777  ...                        3   
2                     1            -7777  ...                        3   
3                     1            -7777  ...                        3   
4                     1            -7777  ...                        3   
...                 ...              ...  ...                      ...   
127015                1            -7777  ...                       15   
127016                1            -7777  ...                       15   
127017                1            -7777  ...                       16   
127018                1            -7777  ...                       16   
127019                1            -7777  ...                       16   

        DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
0                         -9999                        0   
1                         -9999                        0   
2                         -9999                        0   
3                             0                        0   
4                             0                        0   
...                         ...                      ...   
127015                        0                        0   
127016                        0                        0   
127017                        0                        0   
127018                        0                        0   
127019                        0                        0   

        DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
0                         -9999                    -9999   
1                         -9999                    -9999   
2                         -9999                    -9999   
3                             0                        0   
4                             0                        0   
...                         ...                      ...   
127015                        0                        0   
127016                        0                        0   
127017                        0                        0   
127018                        0                        0   
127019                        0                        0   



### Concat
   - `concat` is a function in Pandas used for concatenating two or more DataFrames along a particular axis (either rows or columns).
   - It doesn't perform any merging based on values; instead, it concatenates DataFrames along an axis. You can concatenate DataFrames vertically (along rows) or horizontally (along columns).
   - You can concatenate DataFrames even if they have different indices, and Pandas will create a new index for the resulting DataFrame.

   Example:
   ```python
   result = pd.concat([df1, df2], axis=1)
   ```
   

First, you will see a basic concatenation along axis 0.

In [91]:
double_precip = pd.concat([precip_one_station, precip_one_station])
double_precip.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
1460  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1461  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
1462  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
1463  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
1464  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

      DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
1460             -666            -66.6             0.16             -666   
1461             -666            -66.6             0.16             -666   
1462             -666            -66.6             0.16             -666   
1463             -666            -66.6             0.16             -666   
1464             -666            -66.6             0.17             -666   

      DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-PRCP-PCTALL-GE100HI  \
1460            -66.6             0.44  ...                       11   
1461            -66.6             0.44  ...                       11   
1462            -66.6             0.45  ...                       11   
1463            -66.6             0.45  ...                       11   
1464            -66.6             0.46  ...                       11   

      DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
1460                        4                        0   
1461                        4                        0   
1462                        4                        0   
1463                        4                        0   
1464                        4                        0   

      DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
1460                        3                        3   
1461                        3                        3   
1462                        3                        3   
1463                        3                        2   
1464                        3                        2   

      DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  \
1460                        9                        6   
1461                       10                        6   
1462                       10                        6   
1463                       10                        6   
1464                       10                        6   

      DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
1460                        0                    -9999   
1461                        0                    -9999   
1462                        0                    -9999   
1463                        0                    -9999   
1464                        0                    -9999   

      DLY-SNOW-PCTALL-GE050TI  
1460                    -9999  
1461                    -9999  
1462                    -9999  
1463                    -9999  
1464                    -9999  

[5 rows x 29 columns]

To reset the index, use the `ignore_index` optional parameter.

In [92]:
reindexed = pd.concat(
    [precip_one_station, precip_one_station], ignore_index=True
)
reindexed.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100101             0.04   
1  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100102             0.05   
2  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100103             0.05   
3  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100104             0.05   
4  GHCND:USC00045721  MITCHELL CAVERNS CA US  20100105             0.05   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0             -666            -66.6             0.16             -666   
1             -666            -66.6             0.16             -666   
2             -666            -66.6             0.16             -666   
3             -666            -66.6             0.16             -666   
4             -666            -66.6             0.17             -666   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-PRCP-PCTALL-GE100HI  \
0            -66.6             0.44  ...                       11   
1            -66.6             0.44  ...                       11   
2            -66.6             0.45  ...                       11   
3            -66.6             0.45  ...                       11   
4            -66.6             0.46  ...                       11   

   DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  DLY-SNWD-PCTALL-GE003WI  \
0                        4                        0                        3   
1                        4                        0                        3   
2                        4                        0                        3   
3                        4                        0                        3   
4                        4                        0                        3   

   DLY-SNWD-PCTALL-GE005WI  DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  \
0                        3                        9                        6   
1                        3                       10                        6   
2                        3                       10                        6   
3                        2                       10                        6   
4                        2                       10                        6   

   DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  DLY-SNOW-PCTALL-GE050TI  
0                        0                    -9999                    -9999  
1                        0                    -9999                    -9999  
2                        0                    -9999                    -9999  
3                        0                    -9999                    -9999  
4                        0                    -9999                    -9999  

[5 rows x 29 columns]

When axis labels for the axis you are **not** concatenating along don't match (for example, column labels when concatenating along rows), then all columns are preserved and missing data is filled in with `NaN`. 

In [93]:
outer_joined = pd.concat([climate_precip, climate_temp])
outer_joined.head()

STATION            STATION_NAME      DATE  DLY-PRCP-25PCTL  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100101            -6.66   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100102            -6.66   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100103            -6.66   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100104            -6.66   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100105            -6.66   

   DLY-SNWD-25PCTL  DLY-SNOW-25PCTL  DLY-PRCP-50PCTL  DLY-SNWD-50PCTL  \
0           -666.0            -66.6            -6.66           -666.0   
1           -666.0            -66.6            -6.66           -666.0   
2           -666.0            -66.6            -6.66           -666.0   
3          -9999.0          -9999.0            -6.66          -9999.0   
4          -9999.0          -9999.0            -6.66          -9999.0   

   DLY-SNOW-50PCTL  DLY-PRCP-75PCTL  ...  DLY-CLDD-NORMAL  DLY-CLDD-BASE70  \
0            -66.6            -6.66  ...              NaN              NaN   
1            -66.6            -6.66  ...              NaN              NaN   
2            -66.6            -6.66  ...              NaN              NaN   
3          -9999.0            -6.66  ...              NaN              NaN   
4          -9999.0            -6.66  ...              NaN              NaN   

   DLY-CLDD-BASE72  DLY-HTDD-BASE40  DLY-HTDD-BASE45  DLY-HTDD-BASE50  \
0              NaN              NaN              NaN              NaN   
1              NaN              NaN              NaN              NaN   
2              NaN              NaN              NaN              NaN   
3              NaN              NaN              NaN              NaN   
4              NaN              NaN              NaN              NaN   

   DLY-HTDD-BASE55  DLY-HTDD-BASE57  DLY-HTDD-BASE60  DLY-HTDD-NORMAL  
0              NaN              NaN              NaN              NaN  
1              NaN              NaN              NaN              NaN  
2              NaN              NaN              NaN              NaN  
3              NaN              NaN              NaN              NaN  
4              NaN              NaN              NaN              NaN  

[5 rows x 47 columns]

In [94]:
inner_joined = pd.concat([climate_temp, climate_precip], join="inner")
inner_joined.head()

STATION            STATION_NAME      DATE
0  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100101
1  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100102
2  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100103
3  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100104
4  GHCND:USC00049099  TWENTYNINE PALMS CA US  20100105

In [95]:
inner_joined.shape

(278130, 3)

To illustrate how this would work with rows, concatenate along columns instead:

In [100]:
inner_joined_cols = pd.concat(
    [climate_temp, climate_precip], axis="columns", join="inner"
)
inner_joined_cols.head()

STATION            STATION_NAME ELEVATION  LATITUDE   LONGITUDE  \
0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   
4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806  -116.03694   

       DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  DLY-CLDD-BASE55  \
0  20100101                6                2            -7777   
1  20100102                6                2                1   
2  20100103                6                2                1   
3  20100104                6                2                1   
4  20100105                6                2                1   

   DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  DLY-SNWD-PCTALL-GE001WI  \
0            -7777  ...                        3                    -9999   
1            -7777  ...                        3                    -9999   
2            -7777  ...                        3                    -9999   
3            -7777  ...                        3                        0   
4            -7777  ...                        3                        0   

   DLY-SNWD-PCTALL-GE010WI  DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
0                        0                    -9999                    -9999   
1                        0                    -9999                    -9999   
2                        0                    -9999                    -9999   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  DLY-SNOW-PCTALL-GE100TI  \
0                    -9999                    -9999                        0   
1                    -9999                    -9999                        0   
2                    -9999                    -9999                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   DLY-SNOW-PCTALL-GE030TI  DLY-SNOW-PCTALL-GE050TI  
0                    -9999                    -9999  
1                    -9999                    -9999  
2                    -9999                    -9999  
3                        0                        0  
4                        0                        0  

[5 rows x 50 columns]

In [101]:
inner_joined_cols.shape

(127020, 50)

You can also use the `keys` parameter to set hierarchical axis labels which can be used, for example, to preserve original labels while maintaining labels that tell you which dataset each row or column came from.

In [102]:
hierarchical_keys = pd.concat(
    [climate_temp, climate_precip], keys=["temp", "precip"]
)
hierarchical_keys.head()

STATION            STATION_NAME ELEVATION  LATITUDE  \
temp 0  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
     1  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
     2  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
     3  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   
     4  GHCND:USC00049099  TWENTYNINE PALMS CA US       602  34.12806   

         LONGITUDE      DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  \
temp 0  -116.03694  20100101              6.0              2.0   
     1  -116.03694  20100102              6.0              2.0   
     2  -116.03694  20100103              6.0              2.0   
     3  -116.03694  20100104              6.0              2.0   
     4  -116.03694  20100105              6.0              2.0   

        DLY-CLDD-BASE55  DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  \
temp 0          -7777.0          -7777.0  ...                      NaN   
     1              1.0          -7777.0  ...                      NaN   
     2              1.0          -7777.0  ...                      NaN   
     3              1.0          -7777.0  ...                      NaN   
     4              1.0          -7777.0  ...                      NaN   

        DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
temp 0                      NaN                      NaN   
     1                      NaN                      NaN   
     2                      NaN                      NaN   
     3                      NaN                      NaN   
     4                      NaN                      NaN   

        DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
temp 0                      NaN                      NaN   
     1                      NaN                      NaN   
     2                      NaN                      NaN   
     3                      NaN                      NaN   
     4                      NaN                      NaN   

        DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  \
temp 0                      NaN                      NaN   
     1                      NaN                      NaN   
     2                      NaN                      NaN   
     3                      NaN                      NaN   
     4                      NaN                      NaN   

        DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
temp 0                      NaN                      NaN   
     1                      NaN                      NaN   
     2                      NaN                      NaN   
     3                      NaN                      NaN   
     4                      NaN                      NaN   

        DLY-SNOW-PCTALL-GE050TI  
temp 0                      NaN  
     1                      NaN  
     2                      NaN  
     3                      NaN  
     4                      NaN  

[5 rows x 47 columns]

In [103]:
hierarchical_keys.tail()

STATION            STATION_NAME ELEVATION LATITUDE  \
precip 151105  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   
       151106  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   
       151107  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   
       151108  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   
       151109  GHCND:USC00046006  MOUNT WILSON CBS CA US       NaN      NaN   

              LONGITUDE      DATE  DLY-CLDD-BASE45  DLY-CLDD-BASE50  \
precip 151105       NaN  20101227              NaN              NaN   
       151106       NaN  20101228              NaN              NaN   
       151107       NaN  20101229              NaN              NaN   
       151108       NaN  20101230              NaN              NaN   
       151109       NaN  20101231              NaN              NaN   

               DLY-CLDD-BASE55  DLY-CLDD-BASE57  ...  DLY-PRCP-PCTALL-GE100HI  \
precip 151105              NaN              NaN  ...                     62.0   
       151106              NaN              NaN  ...                     62.0   
       151107              NaN              NaN  ...                     63.0   
       151108              NaN              NaN  ...                     64.0   
       151109              NaN              NaN  ...                     64.0   

               DLY-SNWD-PCTALL-GE001WI  DLY-SNWD-PCTALL-GE010WI  \
precip 151105                  -9999.0                  -9999.0   
       151106                  -9999.0                  -9999.0   
       151107                  -9999.0                  -9999.0   
       151108                  -9999.0                  -9999.0   
       151109                  -9999.0                  -9999.0   

               DLY-SNWD-PCTALL-GE003WI  DLY-SNWD-PCTALL-GE005WI  \
precip 151105                  -9999.0                  -9999.0   
       151106                  -9999.0                  -9999.0   
       151107                  -9999.0                  -9999.0   
       151108                  -9999.0                  -9999.0   
       151109                  -9999.0                  -9999.0   

               DLY-SNOW-PCTALL-GE001TI  DLY-SNOW-PCTALL-GE010TI  \
precip 151105                  -9999.0                  -9999.0   
       151106                  -9999.0                  -9999.0   
       151107                  -9999.0                  -9999.0   
       151108                  -9999.0                  -9999.0   
       151109                  -9999.0                  -9999.0   

               DLY-SNOW-PCTALL-GE100TI  DLY-SNOW-PCTALL-GE030TI  \
precip 151105                  -9999.0                  -9999.0   
       151106                  -9999.0                  -9999.0   
       151107                  -9999.0                  -9999.0   
       151108                  -9999.0                  -9999.0   
       151109                  -9999.0                  -9999.0   

               DLY-SNOW-PCTALL-GE050TI  
precip 151105                  -9999.0  
       151106                  -9999.0  
       151107                  -9999.0  
       151108                  -9999.0  
       151109                  -9999.0  

[5 rows x 47 columns]